[workspace]
members = ["programs/proofpay"]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
proofpay = "11111111111111111111111111111111"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
